// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcaxvPwS_iOK4imSTGkElLRsW3fK5Xm3s',
    appId: '1:193701428947:web:013a2177628a6c99949e26',
    messagingSenderId: '193701428947',
    projectId: 'donat-em-a9d65',
    authDomain: 'donat-em-a9d65.firebaseapp.com',
    storageBucket: 'donat-em-a9d65.appspot.com',
    measurementId: 'G-4FKTCKC182',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3PW_EBQXELptqsMxR0YCgLC1eZQbYFMo',
    appId: '1:193701428947:android:81ff3e573ce420a2949e26',
    messagingSenderId: '193701428947',
    projectId: 'donat-em-a9d65',
    storageBucket: 'donat-em-a9d65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXxVolPDqv2PuFQbBS0FqDv07aljmwcXo',
    appId: '1:193701428947:ios:2c97511991b6bb1b949e26',
    messagingSenderId: '193701428947',
    projectId: 'donat-em-a9d65',
    storageBucket: 'donat-em-a9d65.appspot.com',
    androidClientId: '193701428947-dpqolt8j59bmkm9dfslo8p44de5dmoed.apps.googleusercontent.com',
    iosClientId: '193701428947-hulbaanmq02tm3ftjr36nb3tufa4re1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.donatem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXxVolPDqv2PuFQbBS0FqDv07aljmwcXo',
    appId: '1:193701428947:ios:3c28d93d7a8e0212949e26',
    messagingSenderId: '193701428947',
    projectId: 'donat-em-a9d65',
    storageBucket: 'donat-em-a9d65.appspot.com',
    androidClientId: '193701428947-dpqolt8j59bmkm9dfslo8p44de5dmoed.apps.googleusercontent.com',
    iosClientId: '193701428947-auj6koqqt10c4od48ccikaqu4cde0g2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.donatem.RunnerTests',
  );
}
